function myFunction() {
    myvar = setTimeout(showpage, 3000);
    if (window.location.href == "file:///C:/Users/ASUS/Desktop/Online%20Cafe/categoryresult.html") {
        menuListResult();
    }
}

function showpage() {
    document.getElementById('loader').style.display = "none";
    document.getElementById('mainContainer').style.display = "block";
    document.body.style.backgroundColor = "#f7f7f7";
}

function openNav() {
    document.getElementById('mySideNav').style.width = "250px";
}
function closeNav() {
    document.getElementById('mySideNav').style.width = '0px';
}

var categoryResult;
function categorySearch() {
    var pattern = /^[6-9]\d{9}$/;
    var res = pattern.test(document.getElementById('number').value);
    if (res) {
        var categoryVal = document.getElementById('menuList').value;
        if (categoryVal == 'selectcategory') {
            alert('Please Select any Category');
            return false;
        }
        else {
            sessionStorage.setItem(categoryResult, categoryVal);
            alert(categoryVal + ": - Available");
            return true;
        }
    }
    else{
        window.alert('Invalid Mobile Number');
        return false;
    }

}
function menuListResult() {
    categoryResult = sessionStorage.getItem(categoryResult);
    // console.log(sessionStorage.getItem(categoryResult));
    switch (categoryResult) {
        case 'starters':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/soup.jpg" alt=""><h1>Soup <span>&#8377;125</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/s-img-6.jpg" alt=""><h1>Healty Breakfast <span>&#8377;25</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/honeychillipotato.jpg" alt=""><h1>Honey Chilli Potato <span>&#8377;190</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/babycornchilli.jfif" alt=""><h1>Baby Corn Chilli <span>&#8377;200</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/vegspringrolls.jfif" alt=""><h1>Veg Spring Rolls <span>&#8377;195</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/cheesygarlicbread.jpg" alt=""><h1>Cheesy Garlic Bread <span>&#8377;135</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/frenchfries.jfif" alt=""><h1>French Fries <span>&#8377;99</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'appetizers':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/s-img-1.jpg" alt=""><h1>Tasty Burger <span>&#8377;60</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/samosa.jpg" alt=""><h1>Samosa <span>&#8377;30</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/onionbhaji.jfif" alt=""><h1>Onion Bhaji <span>&#8377;20</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/vadapav.jpg" alt=""><h1>Vada Pav <span>&#8377;40</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/pavbhaji.jpg" alt=""><h1>Pav Bhaji <span>&#8377;60</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'chinese':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/vegnoodles.jpg" alt=""><h1>Veg Noodles <span>&#8377;125</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/hakkanoodles.jpg" alt=""><h1>Veg Hakka Noodles <span>&#8377;145</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/chickennoodles.webp" alt=""><h1>Chicken Noodles <span>&#8377;185</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/vegmanchurian.png" alt=""><h1>Veg Manchurian <span>&#8377;170</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/honeychillipotato.jpg" alt=""><h1>Honey Chilli Potato <span>&#8377;190</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/babycornchilli.jfif" alt=""><h1>Baby Corn Chilli <span>&#8377;200</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'breads':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/plainnaan.jfif" alt=""><h1>Plain Naan <span>&#8377;50/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/butternaan.jpg" alt=""><h1>Butter Naan <span>&#8377;60/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/plainroti.jpg" alt=""><h1>Plain Roti <span>&#8377;10/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/butterroti.jpg" alt=""><h1>Butter Roti <span>&#8377;20/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/lachhaparatha.jfif" alt=""><h1>Lachha Parantha <span>&#8377;20/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/butterlachhaparatha.jfif" alt=""><h1>Butter Lachha Parantha <span>&#8377;40/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/aaloparatha.jpg" alt=""><h1>Aalo Parantha <span>&#8377;20/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/gobhiparatha.webp" alt=""><h1>Gobhi Parantha <span>&#8377;20/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/poori.jpg" alt=""><h1>Poori <span>&#8377;5/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'northindian':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/paneerbuttermasala.jfif" alt=""><h1>Paneer Butter Masala <span>&#8377;359</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/kadaipaneer.jpg" alt=""><h1>Kadai Paneer <span>&#8377;259</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/creamyshahipaneer.jpg" alt=""><h1>Creamy Shahi Paneer <span>&#8377;299</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/spicymushroom.jfif" alt=""><h1>Spicy Mushroom <span>&#8377;299</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/dalmakhni.jfif" alt=""><h1>Dal Makhni <span>&#8377;175</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/daltadka.jpg" alt=""><h1>Dal Tadka <span>&#8377;145</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'southindian':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/masaladosa.jfif" alt=""><h1>Masala Dosa <span>&#8377;60</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/idlisambhar.jpg" alt=""><h1>Idli Sambhar <span>&#8377;40</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/meenmurringakkacurry.webp" alt=""><h1>Meen Murringakka Curry <span>&#8377;90</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/andhrastylechickencurry.jpg" alt=""><h1>Andhra Style Chicken Curry <span>&#8377;120</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'drinks':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/coke.jpg" alt=""><h1>Coke <span>&#8377;99</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/sprite.jpg" alt=""><h1>Sprite <span>&#8377;99</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/maaza.jfif" alt=""><h1>Maaza <span>&#8377;99</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/virginmojito.jpg" alt=""><h1>Virgin Mojito <span>&#8377;199</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/classicbluelagoon.jfif" alt=""><h1>Classic Blue Lagoon <span>&#8377;199</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/fruit&vinegarmocktail.jpg" alt=""><h1>Fruit & Vinegar Mocktail <span>&#8377;205</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/pinacolada.jfif" alt=""><h1>Pina Colada <span>&#8377;205</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/coldcoffee.jpg" alt=""><h1>Cold Coffee <span>&#8377;205</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'desserts':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/s-img-3.jpg" alt=""><h1>Cold Ice-cream <span>&#8377;120</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/s-img-5.jpg" alt=""><h1>Sweets <span>&#8377;220</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/gulabjamun.jfif" alt=""><h1>Gulab Jamun<span>&#8377;12/pcs</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        case 'pizza':
            document.getElementById('menuLists').innerHTML = '<div class="menuItemBox"><img src="Images/farmhouse.jpg" alt=""><h1>Farmhouse <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/mexicangreenwave.jpg" alt=""><h1>Mexican Green Wave <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/deluxeveggie.jpg" alt=""><h1>Deluxe Veggie <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/chickendominator.jpg" alt=""><h1>Chicken Dominator <span>&#8377;394</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/vegextravaganza.jpg" alt=""><h1>Veg Extravaganza <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/chickenpeproni.jpg" alt=""><h1>Chicken Pepperoni <span>&#8377;579</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/peppypaneer.jpg" alt=""><h1>Peppy Paneer <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/veggieparadise.jfif" alt=""><h1>Veggie Paradise <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/inditandooripaneer.jpg" alt=""><h1>Indi Tandoori Paneer <span>&#8377;440</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div><div class="menuItemBox"><img src="Images/pepperbarbequechicken.webp" alt=""><h1>Pepper Barbeque Chicken <span>&#8377;399</span></h1><button class="menuCategoriesBtn" type="submit" onclick="window.location.href=`order.html`;">Order Here</button></div>';
            break;
        default:
            document.getElementById('empty').innerHTML = "Please Select any Category From Home Page";
            document.getElementById('menuLists').style.display = 'none';
            document.getElementById('menuContainer').style.display = 'none';
            document.body.style.display = 'block';
            break;
    }
    sessionStorage.clear();
}